# -*- mode: ruby -*-
# vi: set ft=ruby :

base_box = ENV["BASE_BOX"] || "ubuntu/xenial64"
bridge = ENV["BRIDGE"] || "enp7s0"
mem = ENV["MEMORY"] || 6000
cores = ENV["CPU_CORES"] || 4

Vagrant.configure("2") do |config|
  config.vm.box = base_box
  config.vm.hostname = "dev"
  config.vm.network "public_network", "bridge": bridge
  config.vm.provider "virtualbox" do |v|
    v.memory = mem
    v.cpus = cores
  end

  config.vm.provision "setup", run: "once", type: "ansible" do |a|
    a.playbook = "./provisioning/provision.yaml"
  end
