workspace:
  base: /go
  path: /go/src/github.com/GoingFast/test6
pipeline:
  # gateway-to-hub:
  #   image: plugins/docker
  #   dockerfile: docker/Dockerfile.gateway
  #   secrets: [ docker_username, docker_password ]
  #   repo: risla8/gateway
  #   tags:
  #     - latest
  #     - ${DRONE_COMMIT_SHA:0:8}

  # crud-to-hub:
  #   image: plugins/docker
  #   dockerfile: docker/Dockerfile.crud
  #   secrets: [ docker_username, docker_password ]
  #   repo: risla8/crud
  #   tags:
  #     - latest
  #     - ${DRONE_COMMIT_SHA:0:8}

  deploy:
    image: quay.io/ipedrazas/drone-helm
    skip_tls_verify: true
    chart: ./k8s/charts/app
    release: ${DRONE_BRANCH}
    prefix: dev
    debug: true
    namespace: dev
    secrets: [ api_server, kubernetes_token ]
