# Default values for envoy-private-frontproxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: envoyproxy/envoy-alpine
  tag: latest
  pullPolicy: IfNotPresent

envoy:
  config:
    httpPort: 80
    httpsPort: 443
    adminPort: 9901
    mapName: envoy-private-fp
    fileName: envoy-fp.yaml
    mountPath: /home/
    clusterName: envoy-private-fp
    domains: '["*"]'
    lb_policy: LEAST_REQUEST
    crud_addr: crud

service:
  httpPort: 80
  httpsPort: 443
  adminPort: 9901

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
