FROM golang:alpine AS builder
COPY . /go/src/github.com/GoingFast/test6
WORKDIR /go/src/github.com/GoingFast/test6/http
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o gateway

FROM alpine
COPY --from=builder /go/src/github.com/GoingFast/test6/http .
ENTRYPOINT ["./gateway"]
