FROM golang:alpine AS builder
COPY . /test6
WORKDIR /test6/cmd/client
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o client -mod=vendor

FROM alpine
COPY --from=builder /test6/cmd/client .
ENTRYPOINT ["./client"]
