FROM golang:alpine AS builder
COPY . /test6
WORKDIR /test6/cmd/server
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o server -mod=vendor

FROM alpine
COPY --from=builder /test6/cmd/server .
ENTRYPOINT ["./server"]
