# Default values for gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: risla8/gateway
  tag: latest
  pullPolicy: Never

envoy:
  config:
    fileName: gateway.yaml
    mapName: gateway-config
    domains: '["*"]'
    lb_policy: LEAST_REQUEST
    port: 80
    clusterName: gateway

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
