apiVersion: v1
kind: Service
metadata:
  name: {{ include "crud.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "crud.name" . }}
    helm.sh/chart: {{ include "crud.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.crud.envoy.config.port }}
      targetPort: sidecar
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "crud.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
