apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "envoy-private-frontproxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "envoy-private-frontproxy.name" . }}
    helm.sh/chart: {{ include "envoy-private-frontproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "envoy-private-frontproxy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "envoy-private-frontproxy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }} 
    spec:
      volumes:
        - name: {{ .Values.envoy.config.mapName }}
          configMap:
            name: {{ .Values.envoy.config.mapName }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.envoy.config.httpPort }}
              protocol: TCP
            - name: https
              containerPort: {{ .Values.envoy.config.httpsPort }}
              protocol: TCP
            - name: admin
              containerPort: {{ .Values.envoy.config.adminPort }}
              protocol: TCP
          volumeMounts:
            - name: {{ .Values.envoy.config.mapName }}
              mountPath: {{ .Values.global.configMountPath}}
          command: ["/usr/local/bin/envoy"]
          args: ["-c {{ .Values.global.configMountPath}}{{ .Values.envoy.config.fileName}}", "--service-cluster {{ .Values.envoy.config.clusterName}}"]
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
