apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-pv-fp-config
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 80
          filter_chains:
            filters:
              - name: envoy.http_connection_manager
                config:
                  stat_prefix: router
                  route_config:
                    name: prod
                    virtual_hosts:
                      - name: local_service
                        domains: ["*"]
                        routes:
                          - match: { prefix: "/crud.CRUDService", grpc: {} }
                            route: { cluster: crud_prod_cluster }
                  http_filters:
                    - name: envoy.router
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 27015
          filter_chains:
            filters:
              - name: envoy.http_connection_manager
                config:
                  stat_prefix: router
                  route_config:
                    name: dev
                    virtual_hosts:
                      - name: local_service
                        domains: ["*"]
                        routes:
                          - match: { prefix: "/crud.CRUDService", grpc: {} }
                            route: { cluster: crud_dev_cluster }
                  http_filters:
                    - name: envoy.router
      clusters:
        - name: crud_prod_cluster
          connect_timeout: 1s
          type: STRICT_DNS
          lb_policy: {{ .Values.envoy.privatefrontproxy.config.lb_policy }}
          hosts:
            - socket_address:
                address: prod-svc-crud.prod
                port_value: 80
          http2_protocol_options: {}
        - name: crud_dev_cluster
          connect_timeout: 1s
          type: STRICT_DNS
          lb_policy: {{ .Values.envoy.privatefrontproxy.config.lb_policy }}
          hosts:
            - socket_address:
                address: dev-svc-crud.dev
                port_value: 80
          http2_protocol_options: {}
