{{- if .Values.svc.enabled}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "svc.fullname" . }}-crud
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "svc.name" . }}
    helm.sh/chart: {{ include "svc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    tier: {{ .Values.tier }}
    svc: crud
spec:
  replicas: {{ .Values.crud.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "svc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      tier: {{ .Values.tier }}
      svc: crud
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "svc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        tier: {{ .Values.tier }}
        svc: crud
    spec:
      containers:
        - name: {{ include "svc.fullname" . }}-crud
          image: "{{ .Values.crud.image.repository }}:{{ .Values.crud.image.tag }}"
          imagePullPolicy: {{ .Values.crud.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
          command:
          - "/bin/sh"
          - "-c"
          - "./crud"
          resources:
{{ toYaml .Values.crud.resources | indent 12 }}
    {{- with .Values.crud.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.crud.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.crud.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
