{{- if .Values.envoy.enabled }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "svc.fullname" . }}-public-frontproxy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "svc.name" . }}
    helm.sh/chart: {{ include "svc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    tier: {{ .Values.tier }}
spec:
  replicas: {{ .Values.envoy.publicfrontproxy.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "svc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      tier: {{ .Values.tier }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "svc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        tier: {{ .Values.tier }}
    spec:
      volumes:
        - name: envoy-pb-fp-config
          configMap:
            name: envoy-pb-fp-config
        - name: envoy-pb-fp-tls
          secret:
            secretName: envoy-pb-fp-tls
      containers:
        - name: {{ include "svc.fullname" . }}-public-frontproxy
          image: "{{ .Values.envoy.publicfrontproxy.image.repository }}:{{ .Values.envoy.publicfrontproxy.image.tag }}"
          imagePullPolicy: {{ .Values.envoy.publicfrontproxy.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
            - name: admin
              containerPort: 9901
              protocol: TCP
          volumeMounts:
            - name: envoy-pb-fp-config
              mountPath: "/home/envoy.yaml"
              subPath: "envoy.yaml"
            - name: envoy-pb-fp-tls
              mountPath: "/home/certs"
          command: ["/usr/local/bin/envoy"]
          args: ["-c /home/envoy.yaml"]
          resources:
{{ toYaml .Values.envoy.publicfrontproxy.resources | indent 12 }}
    {{- with .Values.envoy.publicfrontproxy.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.envoy.publicfrontproxy.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.envoy.publicfrontproxy.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
