apiVersion: v1
kind: ConfigMap
metadata:
  name: crud-cfg
data:
  crud.yaml: |
    static_resources:
      listeners:
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 80
          filter_chains:
            filters:
              - name: envoy.http_connection_manager
                config:
                  stat_prefix: router
                  route_config:
                    name: local_route
                    virtual_hosts:
                      - name: local_service
                        domains: ["*"]
                        routes:
                          - match: { prefix: "/crud.CRUDService", grpc: {} }
                            route: { cluster: crud_cluster }
                  http_filters:
                    - name: envoy.router
      clusters:
        - name: crud_cluster
          connect_timeout: 1s
          type: STRICT_DNS
          lb_policy: {{ .Values.envoy.crud.config.lb_policy }}
          hosts:
            - socket_address:
                address: 127.0.0.1
                port_value: 50051
          http2_protocol_options: {}
