{{- if .Values.envoy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-pb-fp-config
data:
  envoy.yaml: |
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
    static_resources:
      listeners:
        - name: http
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 80
          filter_chains:
            - filters:
                - name: envoy.http_connection_manager
                  config:
                    stat_prefix: router
                    route_config:
                      virtual_hosts:
                        - name: local_route
                          domains: ["*"]
                          routes:
                            - match: { prefix: "/" }
                              redirect: { path_redirect: "/", https_redirect: true }
                    http_filters:
                      - name: envoy.router
                        config: {}
        - name: https
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 443
          filter_chains:
            filters:
              - name: envoy.http_connection_manager
                config:
                  stat_prefix: router
                  route_config:
                    name: local_route
                    virtual_hosts:
                      - name: prod
                        domains: ["prod.gateway.local:30032"]
                        routes:
                          - match: { prefix: "/api/v1/" }
                            route: { prefix_rewrite: "/", cluster: gateway_cluster, timeout: 60s }
                          - match: { prefix: "/api/v1" }
                            route: { prefix_rewrite: "/", cluster: gateway_cluster, timeout: 60s }
                      - name: dev
                        domains: ["dev.gateway.local:30032"]
                        routes:
                          - match: { prefix: "/api/v1/" }
                            route: { prefix_rewrite: "/", cluster: gateway_dev_cluster, timeout: 60s }
                          - match: { prefix: "/api/v1" }
                            route: { prefix_rewrite: "/", cluster: gateway_dev_cluster, timeout: 60s }
                    response_headers_to_add:
                      - header:
                          key: "X-XSS-Protection"
                          value: "1; mode=block"
                      - header:
                          key: "X-Content-Type-Options"
                          value: "nosniff"
                  http_filters:
                    - name: envoy.router
                      config:
                        suppress_envoy_headers: true
                  add_user_agent: true
                  tracing:
                    operation_name: INGRESS
                  idle_timeout: 840s
                  access_log:
                    - name: envoy.file_access_log
                      filter:
                        or_filter:
                          filters:
                            - status_code_filter:
                                comparison:
                                  op: GE
                                  value:
                                    default_value: 500
                                    runtime_key: access_log.access_error.status
                            - duration_filter:
                                comparison:
                                  op: GE
                                  value:
                                    default_value: 1000
                                    runtime_key: access_log.access_error.duration
                            - traceable_filter: {}
                      config:
                        path: "/tmp/access_error.log"
                        format: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%REQ(X-LYFT-USER-ID)%\" \"%RESP(GRPC-STATUS)%\"\n"
            tls_context:
              common_tls_context:
                tls_certificates:
                  - certificate_chain:
                      filename: "/home/certs/tls.crt"
                    private_key:
                      filename: "/home/certs/tls.key"
      clusters:
        - name: gateway_cluster
          connect_timeout: 1s
          type: STRICT_DNS
          dns_lookup_family: V4_ONLY
          lb_policy: {{ .Values.envoy.publicfrontproxy.config.lb_policy }}
          hosts:
            - socket_address:
                address: prod-svc-gateway.prod
                port_value: 80
          circuit_breakers:
            thresholds:
              - priority: high
                max_connections: 100000
                max_pending_requests: 100000
                max_requests: 60000000
                max_retries: 50
              - priority: default
                max_connections: 100000
                max_pending_requests: 100000
                max_requests: 60000000
                max_retries: 50
          outlier_detection:
            consecutive_5xx: 5
            consecutive_gateway_failure: 5
          upstream_connection_options:
            tcp_keepalive:
              keepalive_probes:
                value: 3 
              keepalive_time:
                value: 30
              keepalive_interval:
                value: 15
        - name: gateway_dev_cluster
          connect_timeout: 1s
          type: STRICT_DNS
          dns_lookup_family: V4_ONLY
          lb_policy: {{ .Values.envoy.publicfrontproxy.config.lb_policy }}
          hosts:
            - socket_address:
                address: dev-svc-gateway.dev
                port_value: 80
          circuit_breakers:
            thresholds:
              - priority: high
                max_connections: 100000
                max_pending_requests: 100000
                max_requests: 60000000
                max_retries: 50
              - priority: default
                max_connections: 100000
                max_pending_requests: 100000
                max_requests: 60000000
                max_retries: 50
          outlier_detection:
            consecutive_5xx: 5
            consecutive_gateway_failure: 5
          upstream_connection_options:
            tcp_keepalive:
              keepalive_probes:
                value: 3 
              keepalive_time:
                value: 30
              keepalive_interval:
                value: 15
{{- end }}
