{{- if .Values.svc.enabled}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "svc.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "svc.name" . }}
    helm.sh/chart: {{ include "svc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    tier: {{ .Values.tier }}
    svc: gateway
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "svc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      tier: {{ .Values.tier }}
      svc: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "svc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        tier: {{ .Values.tier }}
        svc: gateway
    spec:
      containers:
        - name: {{ include "svc.fullname" . }}-gateway
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          env:
            - name: DIAL_ADDR
              value: voyager-{{ include "svc.fullname" .}}-crud:80
          resources:
{{ toYaml .Values.gateway.resources | indent 12 }}
    {{- with .Values.gateway.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.gateway.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.gateway.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
