{{- if .Values.voyager -}}
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
 name: {{ include "svc.fullname" . }}-crud
{{- with .Values.crud.ingress.annotations}}
 annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - tcp:
        port: 80
        backend:
          serviceName: {{ include "svc.fullname" . }}-crud
          servicePort: {{ .Values.crud.service.port }}
  loadBalancerSourceRanges:
    - 10.0.0.0/8
{{- end }}
