{{- if .Values.voyager -}}
{{- $fullName := include "svc.fullname" . -}}
{{- $ingressPath := .Values.gateway.ingress.path -}}
{{- $headerRules := .Values.gateway.ingress.headerRules -}}
{{- $backendRules := .Values.gateway.ingress.backendRules -}}
{{- $port := .Values.gateway.service.port -}}
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: {{ include "svc.fullname" . }}-gateway
{{- with .Values.gateway.ingress.annotations}}
  namespace: {{ $.Release.Namespace }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  tls:
  {{- range .Values.gateway.ingress.tls}}
    - hosts:
      {{- range .hosts}}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  rules:
    {{- range .Values.gateway.ingress.hosts }}
    - host: {{ . | quote}}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}-gateway
              servicePort: {{ $port}}
              headerRules:
              {{- range $headerRules }}
                - {{ . | quote }}
              {{- end }}
              backendRules:
              {{- range $backendRules }}
                - {{ . | quote }}
              {{- end }}
    {{- end }}
{{- end }}
