{{- if .Values.envoy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "svc.fullname" . }}-private-frontproxy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "svc.name" . }}
    helm.sh/chart: {{ include "svc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    tier: {{ .Values.tier }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "svc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    tier: {{ .Values.tier }}
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: admin
      port: 9901
      targetPort: 9901
    - name: dev
      port: 27015
      targetPort: 27015
{{- end }}
