{{- if .Values.svc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "svc.fullname" . }}-crud
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "svc.name" . }}
    helm.sh/chart: {{ include "svc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    tier: {{ .Values.tier }}
    svc: crud
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: grpc
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "svc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    tier: {{ .Values.tier }}
    svc: crud
{{- end }}
