---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gateway.name" . }}
    helm.sh/chart: {{ include "gateway.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gateway.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gateway.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }} 
    spec:
      volumes:
        - name: {{ .Values.envoy.config.mapName }}
          configMap:
            name: {{ .Values.envoy.config.mapName }}
      containers:
        - name: envoy
          image: envoyproxy/envoy-alpine:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: {{ .Values.envoy.config.mapName }}
              mountPath: {{ .Values.global.configMountPath}}
          command: ["/usr/local/bin/envoy"]
          args: ["-c {{ .Values.global.configMountPath}}{{ .Values.envoy.config.fileName}}", "--service-cluster {{ .Values.envoy.config.clusterName}}"]
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: sidecar
              containerPort: {{ .Values.envoy.config.port }}
              protocol: TCP
          env:
            - name: DIAL_ADDR
              value: envoy-private-frontproxy.default.svc.cluster.local:80
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
