---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller-client
  namespace: kube-system
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: tiller-client
  namespace: kube-system
rules:
  - apiGroups: ["extensions", ""]
    resources: ["deployments", "pods", "pods/portforward"]
    verbs: ["get", "list", "patch", "update", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: tiller-client
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: tiller-client
    namespace: kube-system
roleRef:
  kind: Role
  name: tiller-client
  apiGroup: rbac.authorization.k8s.io

